# Use the shared network across all stacks
networks:
  anton-net:
    external: true
services:
  reth:
    build:
      context: .
      dockerfile: reth/reth.dockerfile
    ports:
      - "9420:9420" # metrics
      - "30303:30303" # eth/66 peering
      - "8545:8545" # rpc
      - "8551:8551" # engine
    volumes:
      - "/drives/L1/volumes/l1_el_data/_data:/db"
    networks:
      - anton-net
  lighthouse:
    build:
      context: .
      dockerfile: lighthouse/lighthouse.dockerfile
    ports:
      - "5052:5052/tcp" # rpc
      - "5053:5053/tcp"
      - "5054:5054/tcp" # metrics
    volumes:
      - "/drives/L1/volumes/l1_cl_data/_data:/db"
    networks:
      - anton-net
    depends_on:
      - reth
  eth-metrics-exporter:
    restart: unless-stopped
    image: ethpandaops/ethereum-metrics-exporter:debian-latest
    depends_on:
      - reth
      - lighthouse
    ports:
      - 9300:9300 # metrics
    volumes:
      - ./eth-metrics-exporter.yaml:/root/config.yaml
    command:
      - --config=/root/config.yaml
      - --metrics-port=9300
    networks:
      - anton-net
