{
 "title": "[L1] Consensus Layer - Beacon Processing",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "loki", "label": "Loki", "query": "loki" },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(node_uname_info, network)"
    }
   },
   { "name": "node", "label": "Instance Filter (regex)", "query": ".*" },
   { "name": "quantile", "label": "Histogram Quantile", "query": "0.99" }
  ]
 },
 "panels": [
  { "title": "Worker Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Work Events Rx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Work Events Started",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Work Events Ignored",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(beacon_processor_work_events_ignored_count{network=~\"$network\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Workers Spawned",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_workers_spawned_total{network=~\"$network\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker Idle Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_idle_events_total{network=~\"$network\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Workers Active",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_processor_workers_active_total{network=~\"$network\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time per Task",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (increase(beacon_processor_worker_time_sum{network=~\"$network\", instance=~\"$node\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count per Task",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (increase(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Queue Sizes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Unaggregated Attestation Queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_processor_unaggregated_attestation_queue_total{network=~\"$network\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Aggregated Attestation Queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_processor_aggregated_attestation_queue_total{network=~\"$network\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sync Contribution Queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_processor_sync_contribution_queue_total{network=~\"$network\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reprocessing Queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_processor_reprocessing_queue_total{network=~\"$network\", instance=~\"$node\"}",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Attester Slashing Queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_processor_attester_slashing_queue_total{network=~\"$network\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gossip Block Queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_processor_gossip_block_queue_total{network=~\"$network\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPC Block Queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_processor_rpc_block_queue_total{network=~\"$network\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backfill Chain Segment Queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_processor_backfill_chain_segment_queue_total{network=~\"$network\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Proposer Slashing Queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_processor_proposer_slashing_queue_total{network=~\"$network\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Chain Segment Queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_processor_chain_segment_queue_total{network=~\"$network\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Exit Queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_processor_exit_queue_total{network=~\"$network\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_processor_bls_to_execution_change_queue_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_processor_bls_to_execution_change_queue_total{network=~\"$network\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker Event Processing Times (as per \"Histogram Quantile\" Variable)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "gossip_attestation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"gossip_attestation\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gossip_attestation_batch",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"gossip_attestation_batch\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gossip_aggregate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"gossip_aggregate\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gossip_aggregate_batch",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"gossip_aggregate_batch\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "unknown_block_attestation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"unknown_block_attestation\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "unknown_block_aggregate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"unknown_block_attestation\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "delayed_import_block",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"delayed_import_block\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "chain_segment",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"chain_segment\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "chain_segment_backfill",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"chain_segment_backfill\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "rpc_block",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"rpc_block\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gossip_voluntary_exit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"gossip_voluntary_exit\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "status_processing",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"status_processing\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gossip_block",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"gossip_block\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gossip_proposer_slashing",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"gossip_proposer_slashing\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "blocks_by_roots_request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"blocks_by_roots_request\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "blocks_by_range_request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"blocks_by_range_request\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gossip_attester_slashing",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"gossip_attester_slashing\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gossip_sync_signature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"gossip_sync_signature\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gossip_sync_contribution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"gossip_sync_contribution\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "api_request_p0",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"api_request_p0\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "api_request_p1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_processor_worker_time_bucket{network=~\"${network}\", instance=~\"${node}\", type=\"api_request_p1\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Work Events Received & Started", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "gossip_attestation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_attestation\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_attestation\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "gossip_attestation_batch",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_attestation_batch\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_attestation_batch\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "gossip_aggregate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_aggregate\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_aggregate\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "gossip_aggregate_batch",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_aggregate_batch\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_aggregate_batch\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "unknown_block_attestation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"unknown_block_attestation\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"unknown_block_attestation\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "unknown_block_aggregate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"unknown_block_aggregate\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"unknown_block_aggregate\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "delayed_import_block",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"delayed_import_block\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"delayed_import_block\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "chain_segment",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"chain_segment\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"chain_segment\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "gossip_block",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_block\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_block\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "rpc_block",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"rpc_block\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"rpc_block\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "gossip_voluntary_exit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_voluntary_exit\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_voluntary_exit\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "status_processing",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"status_processing\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"status_processing\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "gossip_attester_slashing",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_attester_slashing\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_attester_slashing\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "gossip_proposer_slashing",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_proposer_slashing\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_proposer_slashing\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "blocks_by_roots_request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"blocks_by_roots_request\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"blocks_by_roots_request\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "blocks_by_range_request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"blocks_by_range_request\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"blocks_by_range_request\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "gossip_sync_contribution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_sync_contribution\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_sync_contribution\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "gossip_sync_signature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_sync_signature\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"gossip_sync_signature\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "api_request_p0",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"api_request_p0\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"api_request_p0\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  },
  {
   "title": "api_request_p1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_processor_work_events_rx_count{network=~\"$network\", instance=~\"$node\", type=\"api_request_p1\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - event received"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{network=~\"$network\", instance=~\"$node\", type=\"api_request_p1\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - work started"
    }
   ]
  }
 ]
}