{
 "title": "[L2] op-node (Full L2 Dash)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Nodes",
    "query": {
     "query": "label_values(op_node_default_up, namespace)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(op_node_default_up, stack_optimism_io_network)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Node version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "op_node_default_info", "legendFormat": "version" }
   ]
  },
  {
   "title": "Last Reorg",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "op_node_default_last_pipeline_reset_unix * 1000"
    }
   ]
  },
  {
   "title": "Seconds per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "1/max(rate(op_node_default_refs_number{type=\"l1_head\", layer=\"l1\"}[$__interval]))",
     "legendFormat": "L1"
    },
    {
     "expr": "1/max(rate(op_node_default_refs_number{type=\"l2_safe\", layer=\"l2\"}[$__interval]))",
     "legendFormat": "Safe L2"
    },
    {
     "expr": "1/max(rate(op_node_default_refs_number{type=\"l2_unsafe\", layer=\"l2\"}[$__interval]))",
     "legendFormat": "Unsafe L2"
    }
   ]
  },
  {
   "title": "Node Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(op_node_default_up)" }
   ]
  },
  {
   "title": "L1 Head (a.k.a. unsafe)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{type=\"l1_head\"})",
     "legendFormat": "L1"
    }
   ]
  },
  {
   "title": "L2 Unsafe L1 Origin",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{type=\"l2_unsafe\", layer=\"l1_origin\"})"
    }
   ]
  },
  {
   "title": "L2 Unsafe",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{type=\"l2_unsafe\", layer=\"l2\"})",
     "legendFormat": "L2 Unsafe"
    }
   ]
  },
  {
   "title": "Throughput (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max(rate(op_node_default_transactions_sequenced_total[$__interval]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Derivation Idle",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_derivation_idle)"
    }
   ]
  },
  {
   "title": "L1 Justified checkpoint (a.k.a. safe)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{type=\"l1_safe\", layer=\"l1\"})",
     "legendFormat": "L1"
    }
   ]
  },
  {
   "title": "L2 Safe L1 Origin",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{type=\"l2_safe\", layer=\"l1_origin\"})"
    }
   ]
  },
  {
   "title": "L2 Safe",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{type=\"l2_safe\", layer=\"l2\"})",
     "legendFormat": "L2 Safe"
    }
   ]
  },
  {
   "title": "Pipeline Resets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_pipeline_resets_total)"
    }
   ]
  },
  {
   "title": "L1 Finalized checkpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{type=\"l1_finalized\", layer=\"l1\"})",
     "legendFormat": "L1"
    }
   ]
  },
  {
   "title": "L2 Finalized L1 Origin",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{type=\"l2_finalized\", layer=\"l1_origin\"})"
    }
   ]
  },
  {
   "title": "L2 Finalized",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{type=\"l2_finalized\", layer=\"l2\"})",
     "legendFormat": "L2 Finalized"
    }
   ]
  },
  {
   "title": "Sync progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{type=\"l1_head\", layer=\"l1\"})",
     "legendFormat": "L1 Head"
    },
    {
     "expr": "max(op_node_default_refs_number{type=~\"l2_unsafe\", layer=\"l2\"})",
     "legendFormat": "Unsafe L2 head"
    },
    {
     "expr": "max(op_node_default_refs_number{type=\"l2_safe\", layer=\"l2\"})",
     "legendFormat": "Safe L2 head"
    },
    {
     "expr": "max(op_node_default_refs_number{type=\"l2_finalized\", layer=\"l2\"})",
     "legendFormat": "L2 Finalized"
    },
    {
     "expr": "max(op_node_default_refs_number{type=\"l2_unsafe\", layer=\"l1_origin\"})",
     "legendFormat": "L2 Unsafe L1 Origin"
    },
    {
     "expr": "max(op_node_default_refs_number{type=\"l2_safe\", layer=\"l1_origin\"})",
     "legendFormat": "L2 Safe L1 Origin"
    },
    {
     "expr": "max(op_node_default_refs_number{type=\"l1_finalized\", layer=\"l1\"})",
     "legendFormat": "L1 Finalized"
    }
   ]
  },
  {
   "title": "Sequencing Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_sequencing_errors_total)"
    }
   ]
  },
  {
   "title": "L1 derived block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{type=\"l1_derived\", layer=\"l1\"})",
     "legendFormat": "L1"
    }
   ]
  },
  {
   "title": "L1 Reorg Depth",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_l1_reorg_depth_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Derivation Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_derivation_errors_total)"
    }
   ]
  },
  {
   "title": "RPC methods requests / second (moving avg.)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(op_node_default_rpc_client_requests_total[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "L1 Reorg depth over time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_l1_reorg_depth_bucket[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publishing Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_sequencing_errors_total)"
    }
   ]
  },
  {
   "title": "Engine API - forkchoiceUpdatedV1 time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_rpc_client_request_duration_seconds_bucket{method=\"engine_forkchoiceUpdatedV1\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "L1 RPC cache adds (+) gets (-) / min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum by (type) (rate(op_node_default_l1_source_cache_add[$__interval])) * 60",
     "legendFormat": "{{type}} add"
    },
    {
     "expr": "sum by (type) (-rate(op_node_default_l1_source_cache_get[$__interval]) * 60)",
     "legendFormat": "{{type}} get"
    }
   ]
  },
  {
   "title": "L2 RPC cache adds (+) gets (-) / min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum by (type) (rate(op_node_default_l2_source_cache_add[$__interval])) * 60",
     "legendFormat": "{{type}} add"
    },
    {
     "expr": "sum by (type) (-rate(op_node_default_l2_source_cache_get[$__interval]) * 60)",
     "legendFormat": "{{type}} get"
    }
   ]
  },
  {
   "title": "Engine API - getPayloadV1 time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_rpc_client_request_duration_seconds_bucket{method=\"engine_getPayloadV1\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Sequencer Block sealing time (less is better)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_sequencer_sealing_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Engine API - newPayloadV1 time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_rpc_client_request_duration_seconds_bucket{method=\"engine_newPayloadV1\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Sequencer Block building time diff (50ms sealing expected)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_sequencer_building_diff_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Peers and streams",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "max(op_node_default_p2p_peer_count)",
     "legendFormat": "peers"
    },
    {
     "expr": "max(op_node_default_p2p_stream_count)",
     "legendFormat": "libp2p streams"
    }
   ]
  },
  {
   "title": "p2p brandwidth usage rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(rate(op_node_default_p2p_bandwidth_bytes_total{direction=\"in\"}[$__interval]))",
     "legendFormat": "inbound"
    },
    {
     "expr": "max(rate(op_node_default_p2p_bandwidth_bytes_total{direction=\"out\"}[$__interval]))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "L2 unsafe payloads queue size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "max(op_node_default_unsafe_payloads_buffer_len)",
     "legendFormat": "Unprocessed buffered L2 unsafe blocks"
    }
   ]
  },
  {
   "title": "L2 unsafe payloads queue memory size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(op_node_default_unsafe_payloads_buffer_mem_size)",
     "legendFormat": "Unprocessed buffered L2 unsafe blocks"
    }
   ]
  },
  {
   "title": "gossip events rate / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum by (type) (rate(op_node_default_p2p_gossip_events_total[$__interval])) * 60",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Peer Scores [Buckets]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "rate(op_node_default_peer_scores_bucket{type=\"total\"}[10m])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}