# Use the shared network across all stacks
networks:
  anton-net:
    external: true
services:
  sepolia-reth:
    build:
      context: .
      dockerfile: reth/reth.dockerfile
    ports:
      - "9421:9421" # metrics
      - "30304:30304" # eth/66 peering
      - "8546:8546" # rpc
      - "8552:8552" # engine
    volumes:
      - "/drives/L1/volumes/sepolia-l1_sepolia_el_data/_data:/db"
    networks:
      - anton-net
  sepolia-lighthouse:
    build:
      context: .
      dockerfile: lighthouse/lighthouse.dockerfile
    ports:
      - "5055:5055/tcp" # rpc
      - "5056:5056/tcp"
      - "5057:5057/tcp" # metrics
    volumes:
      - "/drives/L1/volumes/sepolia-l1_sepolia_cl_data/_data:/db"
    networks:
      - anton-net
    depends_on:
      - sepolia-reth
  sepolia-eth-metrics-exporter:
    restart: unless-stopped
    image: ethpandaops/ethereum-metrics-exporter:debian-latest
    depends_on:
      - sepolia-reth
      - sepolia-lighthouse
    ports:
      - 9301:9301 # metrics
    volumes:
      - ./eth-metrics-exporter.yaml:/root/config.yaml
    command:
      - --config=/root/config.yaml
      - --metrics-port=9301
    networks:
      - anton-net
