# volumes:
#   influxdb-sepolia-store:
networks:
  anton-net:
    external: true
services:
  op-sepolia-geth:
    build:
      context: .
      dockerfile: ./op-geth/op-geth.dockerfile
    ports:
      - "30307:30307/tcp" # eth/66 peering
      - "8548:8548" # rpc
      - "8554:8554" # engine
      - "6061:6061" # metrics
    volumes:
      - "/drives/L2/op-sepolia/op-geth:/db"
    networks:
      - anton-net
  op-sepolia-node:
    build:
      context: .
      dockerfile: ./op-node/op-node.dockerfile
    ports:
      - "9222:9222/tcp" # p2p tcp
      - "7309:7309" # metrics
      - "5059:5059" # rpc
    volumes:
      - "/drives/L2/op-sepolia/op-node:/db"
      - "/drives/L2/op-sepolia/op-node:/safe-db"
    networks:
      - anton-net
    depends_on:
      - op-sepolia-geth
  l2-sepolia-eth-metrics-exporter:
    restart: unless-stopped
    image: ethpandaops/ethereum-metrics-exporter:debian-latest
    depends_on:
      - op-sepolia-geth
      - op-sepolia-node
    ports:
      - 9303:9303 # metrics
    volumes:
      - ./eth-metrics-exporter.yaml:/root/config.yaml
    command:
      - --config=/root/config.yaml
      - --metrics-port=9303
    networks:
      - anton-net
